<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>aside_Continue Editing___guided-tour-container</name>
   <tag></tag>
   <elementGuidId>cea43739-f7b5-4263-abee-a79686054a1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>aside.__guided-tour-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//aside</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>aside</value>
      <webElementGuid>a990b32d-ed72-4bf6-a745-6553403598e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>__guided-tour-container</value>
      <webElementGuid>44ec6c3c-72b1-4a6e-bdae-aa4b2eaea966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;__guided-tour-active&quot;]/aside[@class=&quot;__guided-tour-container&quot;]</value>
      <webElementGuid>a0a7addf-3f76-4577-b357-1f00c2d945ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//aside</value>
      <webElementGuid>29cad1c5-8ce7-455e-9b17-228f8ae8c6c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
